name: Zooni CI
on:
  pull_request:
  push: { branches: master }
  workflow_dispatch:

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build images and create containers
      run: docker compose up -d --build

    - name: Run Tests
      run: docker exec -i theia-app-1 /bin/bash -c "export USGS_USERNAME=usgs && export USGS_PASSWORD=usgs && pytest" & while kill -0 $! > /dev/null 2>&1; do free -m sleep <interval> done
